export { default as exitToAppImg } from './exit_to_app.png';
export { default as negativeLogo } from './negative_logo.png';
export { default as check } from './check.png';
export { default as editIcon } from './pencil.png';
export { default as positiveLogo } from './positive_logo.png';
export { default as classificationBtn } from './classification_btn.png';
export { default as matchsBtn } from './matchs_btn.png';
export { default as loginBtn } from './login_btn.png';
export { default as createMatcBtn} from './create_match_btn.png';
export { default as updateMatcBtn } from './update_match_btn.png';
